### ISSUE TITLE
TempDirectoryContext

### ISSUE THREAD

**Issue by Roscher1** [TonyFlury/py-importjson#37]
Hi Tony,

I've download your py-importjson:

https://github.com/TonyFlury/py-importjson
In the 
test_importjson.py, Z:
from TempDirectoryContext import TempDirectoryContext as TestDirCont
I've an error:
  File "E:/Python/Inst_File/Tony Flury/py-importjson-master/py-importjson-master/tests/test_importjson.py", line 22, in <module>
    from TempDirectoryContext import TempDirectoryContext as TestDirCont
ModuleNotFoundError: No module named 'TempDirectoryContext

can you help me?

Best regards

Günther 

				Klein Ammensleben, 27. Mai  2019

ICS Dr.  G.  Roscher  GmbH
Dr.-Ing., Dipl.-Math. Günther Roscher 
CEO
Am Kirchberg 6
D - 39326 Klein Ammensleben
Tel.: +49 39 202 52 12 6
Fax: +49 39 202 52 12 8
www.ICSRoscher.de
webmaster@ICSRoscher.de

**Comment by TonyFlury** [comment]
Fixed in 0.23
